### ISSUE TITLE
Method not found: 'Microsoft.EntityFrameworkCore.Scaffolding.Metadata.DatabaseModel

### ISSUE THREAD

**Issue by ranthonissen** [JonPSmith/EfCore.TestSupport#23] opened 2019-10-10 13:46 UTC
After upgrading my solution and test project to .NET Core 3.0, I get this error

> System.MissingMethodException : Method not found: 'Microsoft.EntityFrameworkCore.Scaffolding.Metadata.DatabaseModel Microsoft.EntityFrameworkCore.Scaffolding.IDatabaseModelFactory.Create(System.String, System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>)'.
   at TestSupport.EfSchemeCompare.CompareEfSql.GetDatabaseModelViaScaffolder(DbContext[] contexts, String configOrConnectionString, IDesignTimeServices designTimeService)
   at TestSupport.EfSchemeCompare.CompareEfSql.FinishRestOfCompare(String configOrConnectionString, DbContext[] dbContexts, IDesignTimeServices designTimeService)
   at TestSupport.EfSchemeCompare.CompareEfSql.CompareEfWithDb(String configOrConnectionString, DbContext[] dbContexts)
   at TestSupport.EfSchemeCompare.CompareEfSql.CompareEfWithDb(DbContext[] dbContexts)

Is there a plan on updating the project to .NET Core 3?

**Comment by JonPSmith** [comment] 2019-10-10 14:02
I'm working on it now. It's not trivial.

**Comment by ranthonissen** [comment] 2019-10-10 14:09
I thought so...
Thank you for the quick response.

**Comment by JonPSmith** [comment] 2019-10-12 16:46
This is fixed in Version 3.0.0, which is now out.

**Closed as completed by JonPSmith** 2019-10-12 16:46 UTC

**Comment by ranthonissen** [comment] 2019-10-17 12:26
Thank you!
Works as expected

**Comment by mjedrzejek** [comment] 2019-12-27 14:38
I am getting the same error in my test projects (.NET 4.7.2 and also .NET Core 3.1) with:
1. Microsoft.EntityFrameworkCore v.3.1
2. EfCore.TestSupport v.3.1

Is there a plan on introducing the same fix in newer versions?

**Comment by JonPSmith** [comment] 2019-12-29 15:19
Hi @mjedrzejek,

I confirmed that my EfSchemaCompare feature works with .NET Core 3.1, so I expect the problem is that my EfCore.TestSupport library uses NetStandard2.1, which isn't compatible with NET Framework 4.7.2.

To allow me to produce one NuGet library that would work with both EF Core 2 and EF Core 3 I use the NetStandard2.0/ NetStandard2.1 to detect which version of EF Core you are using (EF Core 3.0 needed NetStandard2.1).

I don't plan to change the EF Core 3 version of the library to support NetStandard2.0.

**Comment by mjedrzejek** [comment] 2019-12-29 22:53
OK, thanks for the info!
